server:
  port: 8100
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/oms-goods?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    password: root
    username: root

mybatis-plus:
  type-aliases-package: cn.dian1.**.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
logging:
  level:
    root: debug
